[package]
name = "acid-rain"
version = "0.1.0"
authors = ["PHO <pho at cielonegro dot org>"]
edition = "2018"
description = "TTY-based factory simulation game"
keywords = ["game"]
license = "CC0-1.0"

[dependencies]
clap = "~2"
